name: Python CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PYTHON_VERSION: 3.8
      IMAGE_NAME: cataluniat1/django1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lint with flake8
        run: |
          # Linting commands with flake8
          # Replace this comment with actual linting commands using flake8

      - name: Test with pytest
        run: |
          pytest  # Ejecutar pruebas con pytest

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
          # Usar el secreto de Docker Hub
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Usar el secreto del token de Docker Hub

      - name: Connect to SSH and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            sudo docker pull ${{ env.IMAGE_NAME }}:latest
            sudo docker-compose -f /home/ubuntu/app/docker-compose.yml up -d
